#!/bin/tcsh


switch ($1)

	case feldkamp:
	rsync -av --exclude 'libgiraffe*' --exclude 'testsuite' --exclude 'xcca' --exclude '*.o' --exclude '*.os' --exclude '*.dylib' --exclude 'xcode' --exclude 'giraffe.xcodeproj' --exclude '.DS_Store' --exclude '.git' --exclude '.sconsign.dblite' --exclude 'edf_support/*.o' --exclude 'edf_support/*.os' . feldkamp@psexport.slac.stanford.edu:giraffe/
	breaksw

	case sellberg:
	rsync -av --delete --exclude 'libgiraffe*' --exclude 'testsuite' --exclude 'xcca' --exclude '*.o' --exclude '*.os' --exclude '*.dylib' --exclude '*~' --exclude 'xcode' --exclude 'giraffe.xcodeproj' --exclude '.DS_Store' --exclude '.git*' --exclude '.sconsign.dblite' --exclude 'edf_support/*.o' --exclude 'edf_support/*.os' . sellberg@psexport.slac.stanford.edu:~/source/giraffe/
	breaksw

endsw
