#!/bin/bash


case $1 in 

	"feldkamp" )
		rsync -av --exclude 'libgiraffe*' --exclude 'testsuite' --exclude 'filehandler' --exclude 'xcca' --exclude '*.o' --exclude '*.os' --exclude '*.dylib' --exclude 'xcode' --exclude 'giraffe.xcodeproj' --exclude '.DS_Store' --exclude '.git' --exclude '.sconsign.dblite' --exclude 'edf_support/*.o' --exclude 'edf_support/*.os' . feldkamp@psexport.slac.stanford.edu:giraffe/
	;;

	"sellberg" )
		rsync -av --delete --exclude 'libgiraffe*' --exclude 'testsuite' --exclude 'xcca' --exclude 'filehandler' --exclude '*.o' --exclude '*.os' --exclude '*.dylib' --exclude '*~' --exclude 'xcode' --exclude 'giraffe.xcodeproj' --exclude '.DS_Store' --exclude '.git*' --exclude '.sconsign.dblite' --exclude 'edf_support/*.o' --exclude 'edf_support/*.os' . sellberg@psexport.slac.stanford.edu:~/source/giraffe/
	;;

	* )
		echo "Usage: $0 <argument>"
		echo "Allowed arguments include:"
		echo "   feldkamp"
		echo "   sellberg"      
	;;

esac
